// OP Code Encoding Definitions

`define ENDP        15
`define FETCH       16
`define FETCH1      17
`define FETCH2      18
`define CLR         1
`define LOAD        2
`define LOAD2       22
`define STORE       3
`define COPY        4
`define COPY2       23
`define COPY3       24
`define INCR        5
`define ADDI        6
`define ADDI2       25
`define ADDI3       26
`define ADDR        7
`define ADDR2       27
`define ADDR3       28
`define SUBI        8
`define SUBI2       29
`define SUBI3       30
`define SUBR        9
`define SUBR2       31
`define SUBR3       32
`define SHL         10
`define SHL2        33
`define SHL3        34
`define SHR         11
`define SHR2        35
`define SHR3        36
`define JPNZ        12
`define JPNZ2       37
`define OR          13
`define OR2         38
`define OR3         39
