// OP Code Encoding Definitions

`define ENDP        15
`define FETCH       16
`define FETCH1      17
`define FETCH2      18
`define CLR         1
`define LOAD        2
`define LOAD2       22
`define STORE       3
`define COPY        4
`define COPY2       23
`define COPY3       24
`define INCR        5
`define ADDI        6
`define ADDI2       26
`define ADDR        7
`define ADDR2       27
`define SUBI        8
`define SUBI2       28
`define SUBR        9
`define SUBR2       29
`define SHL         10
`define SHL2        30
`define SHR         11
`define SHR2        31
`define JPNZ        12
`define JPNZ2       32
`define OR          13
`define OR2         33
`define NOOP        14
